CREATE TABLE IF NOT EXISTS public.Tasks (
  Id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  TaskText VARCHAR(600) NOT NULL,
  Removed BOOLEAN NOT NULL DEFAULT False,
  TimeStamp DATE NOT NULL,
  PRIMARY KEY (Id));
  
  
CREATE TABLE IF NOT EXISTS public.Notes (
  Id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  NoteText VARCHAR(200) NOT NULL,
  TaskId INT NULL,
  TimeStamp DATE NOT NULL,
  Removed BOOLEAN NOT NULL DEFAULT False,
  PRIMARY KEY (Id),
  CONSTRAINT FK_Task_Note
    FOREIGN KEY (TaskId)
    REFERENCES public.Tasks (Id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);